<a href="https://colab.research.google.com/github/Sahilkushwaha7777/pythonpractice/blob/main/Practicequestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1:

Imagine you are working on a customer management system, and you have first name and last name of a customer storedas separate variable, you are developing a customer management system for a retail store, In your database, you have the first name and last name of a customer stored as seperate variable: first_name="john" and last_name="Doe". how would you concatenate these strings to form the full name "john Doe" for the customer's profile

In [ ]:
first_name= "john"
last_name= "Doe"

full_name= first_name+ " "+ last_name
print(full_name)

john Doe


Question 2:

you have a variable with X with the value 5. How would you reassign X to have the value 10?

In [ ]:
x=5
print("before reassign =", x)

x=10
print("after reassign =", x)


before reassign = 5
after reassign = 10


Question 3:

You have a data containing two record: "quantity" and "price per unit". how would you use arithmetic operator to calculate the total cost for each item , also calculate the total cost? product_1, quantity-5, price_per_unit-rs250, product_2, quantity - 25, price per unit -rs 656, product_3, quantity - 34, price_per_unit - rs274

In [ ]:
#product_1
quantity = 5
price_per_unit = 250
product_1 = quantity * price_per_unit
print("total cost for product 1st :",product_1 ,"rs")

#product_2
quantity = 25
price_per_unit = 656
product_2 = quantity * price_per_unit
print("total cost for product 1st :",product_2 ,"rs")

#product_3
quantity = 34
price_per_unit = 274
product_3 = quantity * price_per_unit
print("total cost for product 1st :",product_3 ,"rs")


print("total cost custumer pay :", product_1 + product_2 + product_3 ,"rs")

total cost for product 1st : 1250 rs
total cost for product 1st : 16400 rs
total cost for product 1st : 9316 rs
total cost custumer pay : 26966 rs


Queation 4:

In a finance based organisation, the task is to calculate the simple interest given the principal amount, interest rate, and time priod. the interst rate is 8%, the principal amount is Rs 15,00,000, and the time period is 3 years. Calculate the simple interest. also, the threshold amount is Rs 1,20,000. please check if the calculated interest is greater  or less than the threshold amount.

In [ ]:
interest_rate = 8
principal_amount = 1500000
time_period =3

simple_interest = (interest_rate * principal_amount * time_period)/100

print("simple interest: ", simple_interest)

threshold_amount = 120000
comparison = threshold_amount < simple_interest
print("threshold amount less is", comparison)

simple interest:  360000.0
threshold amount less is True


Question 5:

Write a python program to calculate the area of circle with a radius of 12cm

In [ ]:
pi = 3.14
rad = 12
print("area of circle : ", pi * rad * rad)

area of circle :  452.15999999999997


Question 6:

In a game application , the player score is stored as afloating point number. however, for leaderboard display, you need to convert the score to an integer, How would you use the int() function to convert the player 's score from floating-point to integer format? pls solve this with code, player score = 1234.455

In [ ]:
player_score = 1234.455
print("the player score is", int(player_score))

the player score is 1234


Question 7:

In a customer relationship management (CRM) system for a retail company, you have a database containing customer record. How would you  use the len() function to find the total number of customers in the database, allowing the company to track its customer base?


customer_database = [
    (1, 'john', 'john@example.com'),
    (2, 'ram', 'ram@example.com'),
    (3, 'shyam', 'shyam@example.com')
                ]

In [ ]:
customer_database = [
    (1, 'john', 'john@example.com'),
    (2, 'ram', 'ram@example.com'),
    (3, 'shyam', 'shyam@example.com')
     ]
print("total number of customer is",len(customer_database))

total number of customer is 3


Question 8:

In a finance based organisation, the task is to calculate the simple interest given the principal amount, interest rate, and time priod. the interst rate is 9.43567%, the principal amount is Rs 250,000, and the time period is 3 years. Calculate the simple interest. the final value should be an integer.

In [ ]:
p_amount = 250000
i_rate = 9.43567
t_period = 3

simple_interest = (p_amount * i_rate * t_period)/100
print("the simple interest is", int(simple_interest))

the simple interest is 70767


Question 9:

As part of your role in a data-driven project, you need to take input from the user for their age, weight, and height. However, there's an issue: the user has entered their age as a negative number. You need to correct the age of the user, and after correcting the age, calculate their Basal Metabolic Rate (BMR) using the Harris-Benedict equation for men. Ensure that the final answer of BMR is an integer.

Basal Metabolic Rate (BMR):

Formula (Harris-Benedict equation for men):

BMR = 88.362 + (13.397 * weight in kg) + (4.799* height in cm) - (5.677 * age in years)

In [ ]:
age=int(input("enter your age in year : "))
weight= int(input("enter your weight in kg : "))
height= int(input("enter your height in cm : "))
correct_age=abs(age)
BMR = 88.362 + (13.397 * weight) + (4.799 * height) - (5.677 * age )
print("BMR",int(BMR))

enter your age in year : -20
enter your weight in kg : 54
enter your height in cm : 179
BMR 1784


Question 10:

write a python code for hostel students, ask them to mention their course name and age. for 5 students and their avg age.

In [ ]:
name1 = input("enter your name : ")
course1 = input("enter course name : ")
age1 = int(input("enter your age in year : "))

name2 = input("enter your name : ")
course2 = input("enter course name : ")
age2 = int(input("enter your age in year :"))

name3 = input("enter your name : ")
course3 = input("enter course name : ")
age3 = int(input("enter your age in year : "))
name4 = input("enter your name : ")
course4 = input("enter course name : ")
age4 = int(input("enter your age in year : "))

name5 = input("enter your name : ")
course5 = input("enter course name : ")
age5 = int(input("enter your age in year : "))

avg_age = (age1 + age2 + age3 + age4 +age5)/5
print("average age of 5 studen: ", avg_age)

enter your name : sahil
enter course name : sahil
enter your age in year : 23
enter your name : dshai
enter course name : sdfgd
enter your age in year :34
enter your name : wddfs
enter course name : sfd
enter your age in year : 34
enter your name : fdvds
enter course name : fdvvds
enter your age in year : 11
enter your name : dscds
enter course name : sd c
enter your age in year : 30
average age of 5 studen:  26.4


Question 11:

You are developing a program for a math competition where participants need to solve mathematical expressions and provide the result.
You want to use Python to automate the evaluation process.
Here's how you could approach it:

1) Take input from the participant to enter a mathematical expression

2) evaluate the expression entered by the participant and obtain the result.

3) Display the result to the participant.

In [ ]:
math_expression = input("enter your mathematical expression : ")
solve =  eval(math_expression)
print("the result of expression is : ",solve)
print("partcipate END")

enter your mathematical expression : 2 * 7 + 10
the result of expression is :  24
partcipate END


Question 12:

Suppose you're analyzing a dataset containing information about house prices in a city. Each record includes details such as the house size (inquare feet), number of bedrooms, and price. You want to perform various calculations and manipulations on this dataset using Python.

Answer the following questions:

1) Ask the user 1 & 2 to enter house size, number of rooms they want and Check the data type user has entered

2) Calculate the price of house, if per sq feet is Rs 5000.

3) Threshold price is 75 lakh Rs, which user is paying the price above threshold price.

In [ ]:
#user_1

house_size = float(input("enter house size user_1 in sq_feet : "))
no_of_room = int(input("enter no. of room user_1 : "))
print("housesize data type :",type(house_size))
calculate_price = house_size * 5000
print("calculate price is",calculate_price)
threshold = 7500000
check = calculate_price > threshold
print("the price is above the threshold price : ",check)

#user_2
house_size_2 = float(input("enter house size user_2 in sq_feet : "))
no_of_room_2 = int(input("enter no. of room user_2 : "))
print("no.of room data type :",type(no_of_room_2))
calculate_price = house_size_2 * 5000
print("calculate price is",calculate_price)
check = calculate_price > threshold
print("the price is above the threshold price : ",check)

enter house size user_1 in sq_feet : 5000
enter no. of room user_1 : 34
housesize data type : <class 'float'>
calculate price is 25000000.0
the price is above the threshold price :  True
enter house size user_2 in sq_feet : 300
enter no. of room user_2 : 34
no.of room data type : <class 'int'>
calculate price is 1500000.0
the price is above the threshold price :  False


Question 13:

You are working on a project to analyze stock market data. Create variables to store the stock symbol, current price, and percentage change in price. Then, calculate the new price after a 10% increase using arithmetic operators. Finally, prompt the user to enter their budget using the input() function, convert it to a float using the float() function, and compare it with the new price.

In [ ]:
stock_symbol = "nifty"
current_price = 100
chng_percentage = 10
print("current price is",current_price)

new_price = (10/100+1)*current_price
print("new price after : ",new_price)

user_budget = input("enter your budget : ")
abudget = float(user_budget)
print("new price above the user budget : ",new_price >abudget)

current price is 100
new price after :  110.00000000000001
enter your budget : 344
new price above the user budget :  False


Question 14:

You are working on a project to analyze weather data.

Create variables to store the current temperature,
the minimum temperature recorded, and the maximum temperature recorded.

Determine whether the current temperature is within the range of the minimum and maximum temperatures
recorded using logical operators

In [ ]:
current_temp = int(input("enter the current temperature is : "))
minimum_temp = 15
maximum_temp = 110

check = minimum_temp < current_temp < maximum_temp

print('the temperature in our range : ',check)

enter the current temperature is : 23
the temperature in our range :  True


Question 15:

Develop a temperature converter in Python for a cold storage that converts temperatures between Celsius and Fahrenheit scales.

The program should take a temperature value and a unit (C or F) as input. If the temperature is less than 15 degrees Celsius, inform the user

that the temperature is not convenient. If the temperature is between 24 to 28 degrees Celsius, inform the user that the temperature is convenient.

In [ ]:
temp = float(input("enter the temperature : "))
if temp<15:
  print("the temperature is not convenient")
if 24<=temp<=28:
  print("the temperature is convenient")

enter the temperature : 12
the temperature is not convenient


Question 15 :

Write a program to check whether a person is eligible for voting or not

In [ ]:
age = int(input("enter your age : "))
if age<18:
  print("you are not eligible for vote")
else:
  print("you are eligible for vote")

enter your age : 12
you are not eligible for vote


Question 16:

You are tasked with developing a Python program to manage employee salaries for a company. Your program should calculate the net salary of each employee based on their base salary, deductions, and bonuses. Additionally, employees who have been with the company for more than 5 years are eligible for an additional loyalty bonus, 8% of salary. Deductions of tax will be 12%

Write a Python script that prompts the user to input the following information for each employee:

Base salary

Years of service

After calculating the net salary, the program should print a summary for each employee including their base salary, deductions, bonuses, loyalty bonus (if applicable), and net salary.

In [ ]:
employe = input("enter the employe name :")
base_salary = int(input("enter the base salary : "))
year = int(input("enter how many years to work this company :"))
if year > 5:
  loyalty_bonus = (base_salary/100)*8
  total_salary = base_salary + loyalty_bonus
  tax = (total_salary/100)*12
  net_salary = total_salary - tax
else:
  loyalty_bonus = 0
  total_salary = base_salary + loyalty_bonus
  tax = (total_salary/100)*12
  net_salary = total_salary - tax
print("employe name is ", employe)
print("its base salary is ",base_salary)
print(" and loyalty bonus ",loyalty_bonus)
print("tax which applied on the salary" ,tax)
print("final in hand salary is ", net_salary)

enter the employe name :sahil kushwaha
enter the base salary : 500000
enter how many years to work this company :3
employe name is  sahil kushwaha
its base salary is  500000
 and loyalty bonus  0
tax which applied on the salary 60000.0
final in hand salary is  440000.0


Question 17:

Write a Python program that prompts the user to input a city and displays the famous monument of that city.

Mumbai: Gateway of India

Kolkata: Victoria Memorial

Chennai: Marina Beach

Bangalore: Botanical Garden

Pune: Shaniwar Wada

Write a Python script to implement this functionality.

In [ ]:
a = int(input("""enter the no. which city you want to visit
1 FOR Mumbai:
2 FOR Kolkata:
3 FOR Chennai:
4 FOR Bangalore:
5 FOR Pune: : """))
print("-------------------------")
if a == 1:
  print("Mumbai: Gateway of India")
elif a==2:
  print("Kolkata: Victoria Memorial")
elif a==3:
  print("Chennai: Marina Beach")
elif a==4:
  print("Bangalore: Botanical Garden")
elif a==5:
  print("Pune: Shaniwar Wada")
else:
  print("invalid entry")

enter the no. which city you want to visit
1 FOR Mumbai:
2 FOR Kolkata:
3 FOR Chennai:
4 FOR Bangalore:
5 FOR Pune: : 4
-------------------------
Bangalore: Botanical Garden


Question 18:

Write a Python program to print all the even numbers between 1 and 50 using a while loop

In [ ]:
for i in range(1,51):
  if(i%2==0):
     print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


Question 19:

You are tasked with validating user input for email addresses. Write a Python program that prompts the user to enter an email address. Use a while loop to iterate through the input and check if the email address contains an "@" symbol and a "." symbol. If the email address does not meet these criteria, print "Invalid email address format. Please try again." Otherwise, print "Email address validation passed

In [ ]:
email = input("enter your valid mail")
if "@" in email and "." in email:
  print("email is valid")
else:
  print("email is not valid")

enter your valid mailsahil@gamail.com
email is valid


Question 20:

write a python program for print a table 1 to 10.

In [ ]:
for i in range(11):
  for j in range(1,11):
    print(i,"*",j ,"=" ,i*j)
  print("_________________")

0 * 1 = 0
0 * 2 = 0
0 * 3 = 0
0 * 4 = 0
0 * 5 = 0
0 * 6 = 0
0 * 7 = 0
0 * 8 = 0
0 * 9 = 0
0 * 10 = 0
_________________
1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10
_________________
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
_________________
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
_________________
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
_________________
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
_________________
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
_________________
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
_________________

Question 21:

You are tasked with creating a program to assist shoppers in calculating their total bill at a grocery store. The store offers discounts based on the total purchase amount. Your task is to implement a Python program that takes the price of each item purchased and calculates the total bill, including any applicable discounts.

The store offers the following discount rates based on the total purchase amount:

If the total purchase amount is $100 or more, the customer receives a 10% discount.

If the total purchase amount is between $50 and $99.99, the customer receives a 5% discount.
If the total purchase amount is less than $50, no discount is applied.

Write a Python program to prompt the user to enter the prices of the items they purchased. Use a for loop to iterate through the prices entered and calculate the subtotal. Apply the appropriate discount based on the total purchase amount using if-else statements. Finally, print out the subtotal, discount amount (if any), and the total bill after applying the discount.

In [ ]:
item = int(input("enter the no. of item : "))
total_bill = 0
for i in range(item):
  price = float(input("enter the price of item : "))
  total_bill = total_bill + price
print("the total bill is :", total_bill)
if total_bill > 100:
      discount = (total_bill/100)*10
      total_bill -= discount
      print("discount amount applied in your bill :",discount)
      print("final amount which you paid :",total_bill)
elif 50 <= total_bill and total_bill <= 99.99:
      discount = (total_bill/100)*5
      total_bill -= discount
      print("discount amount applied in your bill :",discount)
      print("final amount which you paid :",total_bill)
else:
  print("you are not applicable for discount")
  print("final amount which you paid :",total_bill)

enter the no. of item : 5
enter the price of item : 123
enter the price of item : 23
enter the price of item : 2
enter the price of item : 3
enter the price of item : 3
the total bill is : 154.0
discount amount applied in your bill : 15.4
final amount which you paid : 138.6


Question 22:

Write a user-defined function to process the exam scores and calculate the following statistics:

The average exam score.
The highest exam score.
The lowest exam score.
The number of students who passed the exam (assuming a passing score is 80 or above).
The number of students who failed the exam.

exam_scores = [85, 92, 78, 90, 88, 95, 82, 79, 87, 91]

In [ ]:
def exam(exam_score):
  average = sum(exam_score)/len(exam_score)
  highest = max(exam_score)
  lowest = min(exam_score)
  len_exam = len(exam_score)
  passed = 0
  for i in range(len_exam):
    if exam_score[i]>=80:
      passed = passed + 1
  failed = len(exam_score) - passed
  return average, highest, lowest, passed, failed

In [ ]:

exam_scores = [85, 92, 78, 90, 88, 95, 82, 79, 87, 91]
average, highest, lowest, passed, failed = exam(exam_scores)
print("average score : ",average)
print("highest score : ",highest)
print("lowest score : ",lowest)
print("no. of student passed : ",passed)
print("no. of student failed : ",failed)

average score :  86.7
highest score :  95
lowest score :  78
no. of student passed :  8
no. of student failed :  2


Question 23:

You are given a dataset of student grades and need to determine the grade distribution.

Question: Write a Python function

grade_distribution (grades) that takes a list of integers representing student grades (0-100). Use a loop to count the number of grades in each grade category:

'Α' (90-100), 'B' (80-89), 'C' (70-79), 'D' (60-69), and 'F' (below 60).

Use if-elif-else statements within the loop to categorize the grades.

Return a dictionary with the counts of each grade category.

In [ ]:
def grade_distribution(grades):
  for grade in grades:
    if grade >= 90 and grade <=100:
      print("its student grade is : A",grade)
    elif grade >= 80 and grade <=89:
      print("its student grade is : B",grade)
    elif grade >= 70 and grade <=79:
      print("its student grade is : C",grade)
    elif grade >= 60 and grade <=69:
      print("its student grade is : D",grade)
    elif grade < 60:
      print("its student grade is : E",grade)
    else:
      print("invalid entry",grade)
  return

In [ ]:
grades = [89,34,98,43,78,98,50,90,400]
grade_distribution(grades)

its student grade is : B 89
its student grade is : E 34
its student grade is : A 98
its student grade is : E 43
its student grade is : C 78
its student grade is : A 98
its student grade is : E 50
its student grade is : A 90
invalid entry 400


Question 24:

You're creating a number guessing game where the computer generates a random number between 1 and 100, and the player has to guess it.

Write Python code to generate a random number between 1 and 100. Use control flow statements and loops to allow the player to guess the number and provide feedback (too high, too low, or correct). Define a user-defined function to encapsulate the game logic and call this function to play the game.

In [ ]:
import random
def game():
  comp_no = random.randint(1, 100)
  print("computer generated numbers : ",comp_no)
  no__of_attempt = 0
  user_no = None
  while user_no != comp_no:

    no__of_attempt +=1
    user_no = int(input("enter the no. between 1 to 100 : "))
    if comp_no < user_no:
         print("user no. is greater than computer number try again because you are selcted older girlfriend")
    elif comp_no > user_no:
         print("user no. is less than computer number try again, because you have not a girlfriend")
    else:
      print("congatulation you select right girlfriend party bro")

In [ ]:
game()

computer generated numbers :  2
user no. is greater than computer number try again because you are selcted older girlfriend
user no. is greater than computer number try again because you are selcted older girlfriend
congatulation you select right girlfriend party bro


Question 25:

You're tasked with creating a program
to calculate the sum of squares of the first n natural numbers, where n is entered by the user.

Write Python code to prompt the user to enter a positive integer n. Use a loop to calculate the sum of squares of the first n natural numbers. Define a user-defined function to encapsulate the sum of squares calculation logic and call this function with the user's input.

In [ ]:
def sum_of_squares(n):
  total = 0
  for i in range(1,n+1):
    square = i**2
    total = total + square
  print("the sum of squares of the first",n, "natural number is",total)
  return


In [ ]:
sum_of_squares(4)

the sum of squares of the first 4 natural number is 30


Question 26:

Write a Python function that takes a date string in the format "YYYY-MM-DD" and returns a tuple containing the year, month, and day as integers.

Example Input: "2024-05-28"

Expected Output: (2024, 5, 28)

In [ ]:
def date_s(date):
  year = date[0:5]
  month= date[6:8]
  day = date[9:11]
  print(year, month, day)
  return year,month,day

In [ ]:
date = "2025-12-20"
date_s(s)

Question 27:

Given the list scores = [55, 89, 76, 65, 93, 50, 72], write a Python expression to create a new list that contains only the scores that are above 70.

In [ ]:
scores = [55, 89, 76, 65, 93, 50, 72]
new_score = []
for score in scores:
  if score > 70:
    new_score.append(score)
  else:
    pass
print(new_score)

[89, 76, 93, 72]


Question 28:

Given the list data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], write a Python expression to get the sum of the first five elements and another expression to reverse the entire list.

In [ ]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum_of_five = sum(data[:5])
data.reverse()
print("sum of five starting element",sum_of_five)
print("reverse of list",data)

sum of five starting element 15
reverse of list [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


Question 29:

Given the list numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

write Python expressions to:

Create a new list with the first half and the second half swapped.
Print the sum of the last three elements.

input -numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

output -

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]

27

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
half = int((len(numbers))/2)
list1 = numbers[:half]
list2 = numbers[half:]
print(list2 + list1)
list2.reverse()
print(list2)

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]
[10, 9, 8, 7, 6]


Question 30:

Task: Data Cleaning

You have a list responses containing responses

from a survey. However, some responses are recorded

as empty strings due to data entry errors.

Your task is to remove these empty responses from the list.

Write Python code to remove all

empty responses from the responses list

responses = ["Yes", "", "No", "", "Maybe", "", "", "Yes", "No",""]

In [ ]:
responses = ["Yes", "", "No", "", "Maybe", "", "", "Yes", "No", ""]
clean = []
for response in responses:
  if response != "":
    clean.append(response)
  else:
    pass

print("clean : ",clean)

clean :  ['Yes', 'No', 'Maybe', 'Yes', 'No']


Question 31:

Data Analysis Scenario:

You have two lists containing exam scores of students from two different classes.

The lists are class1_scores and class2_scores.

You need to analyze the performance

of the classes by calculating the average score for each class.

Write Python code to calculate the average score for each class.

class1_scores = [85, 90, 88, 92, 78]

class2_scores = [75, 82, 80, 85, 79]

In [ ]:
class1_scores = [85, 90, 88, 92, 78]

class2_scores = [75, 82, 80, 85, 79]

average1 = (sum(class1_scores))/len(class1_scores)
average2 = (sum(class2_scores))/len(class2_scores)

print("average score of first class",average1)
print("average score of first class",average2)

average score of first class 86.6
average score of first class 80.2


Question 32:

Given two lists

list1= [[1, 2], [3, 4], [5, 6]) and list2 = [[7, 8], [9, 10]],

concatenate them into a single list of lists.

In [ ]:
list1= [[1, 2], [3, 4], [5, 6]]
list2 = [[7, 8], [9, 10]]
print(list1 + list2)

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]


Question 33:

Given a list of sentences sentences = ["Hello, world!", "Python is awesome!", "I love coding!"],

join the sentences into a single string separated by newline characters.

output

Joined string with newline characters:

Hello, world!

Python is awesome!

I love coding!

In [ ]:
sentences = ["Hello, world!", "Python is awesome!", "I love coding!"]
for i in sentences:
  print(i)

Hello, world!
Python is awesome!
I love coding!


Question 34:

a. Create a list named data_points containing integers

representing data values: [10, 20, 30, 40, 50].

b. Add the value 60 to the end of the list.

c. Insert the value 5 at the beginning of the list.

d. Remove the value 30 from the list.

e. Print the modified list.

In [ ]:
data_points = [10, 20, 30, 40, 50]
data_points.append(60)
data_points.insert(0,5)
data_points.remove(30)
print(data_points)

[5, 10, 20, 40, 50, 60]


Question 35:

Student Enrollment Status

You are managing student enrollments for a course

and want to determine their enrollment

status based on their course credits. Create a program that:

1) Asks the user to input the number of students.

2 ) Asks the user to input the course credits for each student, storing them in a list.

3) Determines the enrollment status for each student:

"Full-time" if course credits are greater than or equal to 12.

"Part-time" if course credits are less than 12.

4) Prints out the enrollment status for each student.

In [ ]:
no_of_student = int(input("enter no. of students : "))
student_credit = []
for i in range(no_of_student):
  credita = int(input("enter the credit score of student "))
  student_credit.append(credita)
print(student_credit)
full_time = []
part_time = []
for j in range(no_of_student):
  if student_credit[j] >= 12:
    full_time.append(student_credit[j])
  else:
    part_time.append(student_credit[j])
print("full time : ",full_time)
print("part time : ",part_time)
for k in range(no_of_student):
  print(f"student {k+1} that _is{student_credit[k]}")


enter no. of students : 5
enter the credit score of student 23
enter the credit score of student 11
enter the credit score of student 7
enter the credit score of student 34
enter the credit score of student 65
[23, 11, 7, 34, 65]
full time :  [23, 34, 65]
part time :  [11, 7]
student 1 that _is23
student 2 that _is11
student 3 that _is7
student 4 that _is34
student 5 that _is65


Question 36:

Age Group Classification

You are analyzing demographic data and want to classify people into different age groups. Create a program that:

Asks the user to input the number of people.

Asks the user to input the ages of each person, storing them in a list.

Classifies each person into one of the following

age groups: "Child" (age < 18), "Adult" (18 <= age < 65), or "Senior" (age >= 65).

Prints out the number of people in each age group.

In [ ]:
no_of_people = int(input("enter the no. of people : "))
age = []
for i in range(no_of_people):
  age_of_person = int(input("enter the age of this person : "))
  age.append(age_of_person)
print("age list",age)
child = []
adult = []
senior = []
for j in age:
  if j < 18:
    child.append(j)
  elif 18<=j<65:
    adult.append(j)
  else:
    senior.append(j)
print("child :",len(child))
print("adult :",len(adult))
print("senior :",len(senior))

enter the no. of people : 8
enter the age of this person : 4
enter the age of this person : 76
enter the age of this person : 98
enter the age of this person : 65
enter the age of this person : 44
enter the age of this person : 43
enter the age of this person : 20
enter the age of this person : 76
age list [4, 76, 98, 65, 44, 43, 20, 76]
child : 1
adult : 3
senior : 4


Question 37:

String Methods:

a. Create a string variable sentence with any sentence of your choice.

b. Convert the sentence to uppercase.

c. Split the sentence into a list of words.

d. Join the words in the list using a space as the separator.

e. Print the modified sentence.

In [ ]:
letter = input("enter the words : ")
upper = letter.upper()
print("upper",upper)
lst = []
for i in upper:
  lst.append(i)
print(lst)
join = "_".join(lst)
print(join)

enter the words : sahil
upper SAHIL
['S', 'A', 'H', 'I', 'L']
S_A_H_I_L


Question 38:

List Sorting:

a. Create a list named ages containing integers representing ages of individuals.

b. Sort the list in ascending order.

c. Sort the list in descending order.

d. Print the sorted lists.

In [ ]:
ages = [12,3,54,32,6,87,34,1]
ages.sort()
print("the list in ascending order : ",ages)
ages.sort(reverse=True)
print("the list in descending order : ",ages)


the list in ascending order :  [1, 3, 6, 12, 32, 34, 54, 87]
the list in descending order :  [87, 54, 34, 32, 12, 6, 3, 1]


Question 39:

Define two sets students_passed_math and students_passed_science containing student IDs who passed Math and Science respectively. Write Python code to:

1) Print the number of students who passed both Math and Science.

2) Print the student IDs who passed only Math

3) Print the student IDs who passed only Science

4) Determine if students_passed_math is a subset of students_passed_science.

5) Determine if students_passed_science is a superset of students_passed_math.

In [ ]:
students_passed_math = {101,102,103,104,105}
students_passed_science = {104,105,106,107,108}
math= students_passed_math.difference(students_passed_science)
print("the student IDs who passed only Math : ",math)
science = students_passed_science.difference(students_passed_math)
print("the student IDs who passed only Science : ", science)
print(students_passed_math.issubset(students_passed_science))
print(students_passed_science.issubset(students_passed_math))

the student IDs who passed only Math :  {101, 102, 103}
the student IDs who passed only Science :  {106, 107, 108}
False
False


Question 40:

Imagine you are managing an inventory of products in a store.

Create a Python program that initializes a dictionary

to store the following information about products:


Product ID as the key (an integer).

Product name as the value (a string).

Your program should:

Create an empty dictionary.

Prompt the user to enter details for at least 3 products.

Populate the dictionary with the entered product IDs and names.

Display the final dictionary containing all product IDs and names.

In [ ]:
empty = { }
for i in  range(3):
  Product_ID = int(input("enter the product ID : "))
  Product_name = input("enter the product name : ")
  empty[Product_ID] = Product_name
print(empty)

enter the product ID : 1
enter the product name : saag
enter the product ID : 2
enter the product name : pyasa
enter the product ID : 3
enter the product name : puja
{1: 'saag', 2: 'pyasa', 3: 'puja'}


Question 41:

Create a dictionary book_ratings with the following initial data:

'Python Programming': 4.5

'Data Science Handbook': 4.8

'Machine Learning Basics': 4.2

Check if 'Python Programming' is in book_ratings.

Print "Found" if it exists, otherwise print "Not Found".

Use a method to get all keys from book_ratings and

store them in a list titles.

Print the list titles.

In [ ]:
book_ratings = {"Python Programming": 4.5, "Data Science Handbook": 4.8, "Machine Learning Basics": 4.2}
if  "Python Programming" in book_ratings:
  print("found")
else:
  print("not found")



found
dict_keys(['Python Programming', 'Data Science Handbook', 'Machine Learning Basics'])


Question 42:

Create a dictionary fruit_stock with the following items:

'apple': 10

'banana': 15

'orange': 8

'grape': 20

Print each fruit along with its stock count

in the format "Fruit: Stock" using a loop.

OUTPUT

Fruit: apple, Stock: 10

Fruit: banana, Stock: 15

Fruit: orange, Stock: 8

Fruit: grape, Stock: 20

In [ ]:
fruit_stock = {"apple": 10, "banana": 15, "orange": 8, "grape": 20}
for i in fruit_stock:
  print("fruit", i ,"stock",fruit_stock[i])

fruit apple stock 10
fruit banana stock 15
fruit orange stock 8
fruit grape stock 20


Question 43:

Write a Python script to concatenate the following dictionaries to create a now one

In [ ]:
my_dict1 = {101: "sahil", 102:"arpit"}
my_dict2 = {103: "rahil", 104:"narpit"}
my_dict1.update(my_dict2)
print(my_dict1)

{101: 'sahil', 102: 'arpit', 103: 'rahil', 104: 'narpit'}


Question 44:

Print a dictionary where the keys are numbers between 1 and 150 and the values are square of keys

In [ ]:
mydict = {}
for i in range(1,151):
  mydict[i] = i**2
print(mydict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529, 24: 576, 25: 625, 26: 676, 27: 729, 28: 784, 29: 841, 30: 900, 31: 961, 32: 1024, 33: 1089, 34: 1156, 35: 1225, 36: 1296, 37: 1369, 38: 1444, 39: 1521, 40: 1600, 41: 1681, 42: 1764, 43: 1849, 44: 1936, 45: 2025, 46: 2116, 47: 2209, 48: 2304, 49: 2401, 50: 2500, 51: 2601, 52: 2704, 53: 2809, 54: 2916, 55: 3025, 56: 3136, 57: 3249, 58: 3364, 59: 3481, 60: 3600, 61: 3721, 62: 3844, 63: 3969, 64: 4096, 65: 4225, 66: 4356, 67: 4489, 68: 4624, 69: 4761, 70: 4900, 71: 5041, 72: 5184, 73: 5329, 74: 5476, 75: 5625, 76: 5776, 77: 5929, 78: 6084, 79: 6241, 80: 6400, 81: 6561, 82: 6724, 83: 6889, 84: 7056, 85: 7225, 86: 7396, 87: 7569, 88: 7744, 89: 7921, 90: 8100, 91: 8281, 92: 8464, 93: 8649, 94: 8836, 95: 9025, 96: 9216, 97: 9409, 98: 9604, 99: 9801, 100: 10000, 101: 10201, 102: 10404, 103: 10609, 104: 10816, 1

Question 45:

Check whether a given key already exists in a dictionary.

In [ ]:
my_dict1 = {101: "sahil", 102:"arpit"}
print(101 in my_dict1)
print(102 in my_dict1)
print(103 in my_dict1)

True
True
False


# **oops**

In [ ]:
class calculator:
  def sum(self, a, b):
      print(a+b)
  def diff(self, a, b):
      print(a-b)
  def mult(self, a, b):
      print(a*b)

In [ ]:
calc = calculator()

In [ ]:
calc.sum(11,12)
calc.diff(12,11)
calc.mult(11,11)

23
1
121


oop is a way to organize  and structure code by using classes and object to represent real world entities

class :- class is a blue print or template which define property(attrbute) of object

object :- object is instance of class

In [ ]:
class car:
  def start(self):
    print(f"the {self.color} {self.model} car is start")

#object creation and attribute set karna
car1 = car()
car1.model = "honda"
car1.color = "white"

car2 = car()
car2.model = "maruti"
car2.color = "red"

# method call karna
car1.start()
car2.start()

the white honda car is start
the red maruti car is start


# **init function**

init function ekspecial method hai jo class ka object create hone par automatic call hota hai is function ka kaam hai object ki initial property ko set karna aur is function ko construction bhi kehte hai.

In [ ]:
class car:
  def __init__(self, model, color):
    self.model = model
    self.color = color

  def start(self):
    print(f"The {self.color} {self.model} car is starting")

In [ ]:
car1 = car("BMW","Black")

In [ ]:
car1.start()

The Black BMW car is starting


# **Polymorphism** *means many forms*

polymorphism :-  1.compile time polymorphism,

 ----> function overloading

  ---->operator overloading

2.Run time polymorphism

---->method overriding



#polymorphism with function

In [ ]:
class bird:
  def fly(self):
    print("bird is fly")

class airplane:
  def fly(self):
    print("airplane is fly")

In [ ]:
Bird = bird()
Airplane = airplane()

In [ ]:
Bird.fly()
Airplane.fly()

bird is fly
airplane is fly


#run time polymorphism - method over riding

method overiding jab hota hai jab child class apne parent class ka method ko redefine karti hai.
yeh ensure karta hai ki child classs ka method call ho jab object child class ka ho

In [ ]:
#parent class
class animal:
  def make_sound(self):
    print("animal make a sound")

#child class
class dog(animal):
  def make_sound(self):
    print("dog bark")

#child class
class cat(animal):
  def make_sound(self):
    print("cat meww")

In [ ]:
#object creation

Animal = animal()
Dog = dog()
Cat = cat()

In [ ]:
Animal.make_sound()
Dog.make_sound()
Cat.make_sound()

animal make a sound
dog bark
cat meww


#compile time polymorphism - method overloading

python mae method overloading dirct support nahi karta, lekin hum default argument ka use karke ek method ko  multiple tarike sae use kar sakte hai.

In [ ]:
class calculator:
  def add(self, a,b, c=0):
    print(a+b+c)

In [ ]:
calc = calculator()

In [ ]:
calc.add(2,3)

5


In [ ]:
calc.add(3,3,5)

11


************

**Imagine** kariye ek software application jo different types of media files ko play karta hai jaise audio files aur video files. Hum ek MediaPlayer class create kar sakte hain jo play method ko define karega, aur phir AudioPlayer aur VideoPlayer classes inherit karengi MediaPlayer class ko aur play method ko override karengi apne specific behavior ke liye.

In [ ]:
class media_player:
  def play(self):
    print("playing media player")

class Audioplayer(media_player):
  def play(self):
    print("play the music")

class Videoplayer(media_player):
  def play(self):
    print("play the movie")

In [ ]:
media_player1 = media_player()
audio = Audioplayer()
vedio = Videoplayer()

In [ ]:
media_player1.play()
audio.play()
vedio.play()

playing media player
play the music
play the movie


#inheritance

In [ ]:
#single inheritance


class parent:
  def show(self):
    print("this is parent class")

class child(parent):
  def display(self):
    print("this is child class")

In [ ]:
Child = child()

In [ ]:
Child.show()
Child.display()

this is parent class
this is child class


In [ ]:
#multiple inhritane

class mother:
  def show_mother(self):
    print("this is mother class")

class father:
  def show_father(self):
    print("this is father class")

class Child(mother, father):
  def show_child(self):
    print("this is child class")

In [ ]:
child = Child()
child.show_mother()
child.show_father()
child.show_child()

this is mother class
this is father class
this is child class


In [ ]:
#multilevel inheritance

class grandfather:
  def show_gfather(self):
    print("this is grand father class")

class parent(grandfather):
  def show_parent(self):
    print("this is parent class")

class Child(parent):
  def show_child(self):
    print("this is child class")

In [ ]:
child = Child()

In [ ]:
child.show_gfather()
child.show_parent()
child.show_child()

this is grand father class
this is parent class
this is child class


In [ ]:
parent1 = parent()

In [ ]:
parent1.show_gfather()

this is grand father class


In [ ]:
#hierarichal inheritance

class parent:
  def show_parent(self):
    print("this is parent")

class boy(parent):
  def show_boy():
    print("i am boy")

class girl(parent):
  def show_girl():
    print("i am girl")

In [ ]:
childb = boy()
childg = girl()

In [ ]:
childb.show_parent()
childg.show_parent()

this is parent
this is parent


#Numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.ndim)  #check dimension of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
#different dimensional array create

#0 d array
arr1 = np.array(23)
print(arr1)
print(arr1.ndim)

23
0


In [ ]:
#1d array
arr2 = np.array([1,2,3,4,5,6])
print(arr2)
print(arr2.ndim)

[1 2 3 4 5 6]
1


In [ ]:
#2d array
arr3 = np.array([[1,2,3,4],[1.1,2.2,3.5,4.5]])
print(arr3)
print(arr3.ndim)

[[1.  2.  3.  4. ]
 [1.1 2.2 3.5 4.5]]
2


In [ ]:
#3d array
arr4 = np.array([[[1,2,3,4],[8,7,6,5]],[[4,6,4,3],[8,6,4,5]]])
print(arr4)
print(arr4.ndim)

[[[1 2 3 4]
  [8 7 6 5]]

 [[4 6 4 3]
  [8 6 4 5]]]
3


------------
create an array with 5 dimension and verify that it has 5 dimension:

In [ ]:
import numpy as np
arr = np.array([1, 6, 75, 7], ndmin=5) #define the no. of dimension is 5(ndmin is an optional argument used when creating an array with numpy.array(). It specifies the minimum number of dimensions (axes) the resulting NumPy array should have)
print(arr)
print("number of dimension : ",arr.ndim)

[[[[[ 1  6 75  7]]]]]
number of dimension :  5


#indexing of array

In [ ]:
#indexing of 1d array
arr2 = np.array([1,2,3,4,5,6])
print(arr2[2]) #its check the second position indexing start with 0 so print the 3

3


Question 46:

create 1d araay and get the 3rd, 6th and 8th element from the creating array and add them

In [ ]:
a = np.array([41, 32, 53, 86, 45, 26, 86, 43, 13, 65, 75])
print("3rd element : ",a[2])
print("6th element : ",a[5])
print("8th element : ",a[7])
print("total summ of the element is : ", a[2]+a[5]+a[7])

3rd element :  53
6th element :  26
8th element :  43
total summ of the element is :  122


In [ ]:
#indexing of 2d array

arr = np.array([[10, 20, 30, 40, 50],[11, 22, 33, 44, 55]])
print("2nd row of 1st element: ",arr[1,0])

2nd row of 1st element:  11


Question 47:

add the first element  of row 1st and last element of row second

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],[11, 22, 33, 44, 55]])
print("1st element of row 1st : ", arr[0,0])
print("last element of row 2nd : ", arr[1,4])
print("sum of the element : ",arr[0,0]+ arr[1,4] )

1st element of row 1st :  10
last element of row 2nd :  55
sum of the element :  65


In [ ]:
#indexing of 3d array

arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
#access 6, 3, 7, 12
print("acess for 6 : ",arr[0, 1, 2])
print("acess for 3 : ",arr[0, 0, 2])
print("acess for 7 : ",arr[1, 0, 0])
print("acess for 12 : ",arr[1, 1, 2])

acess for 6 :  6
acess for 3 :  3
acess for 7 :  7
acess for 12 :  12


#SLICING OF ARRAY

In [ ]:
#1d array slicing

import numpy as np
a = np.array([41, 32, 53, 86, 45, 26, 86, 43, 13, 65, 75])
print(a[2:5]) # print 53 86 45

#2d array slicing

arr = np.array([[10, 20, 30, 40, 50],[11, 22, 33, 44, 55]])
print(arr[1,0:]) #print all second row

#3d array slicing

arr1 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr1[0,1,1:])

[53 86 45]
[11 22 33 44 55]
[5 6]


In [ ]:
##Data Types in NumPy

#NumPy has some extra data types, and refer to data types with one character, like i for integers,

#i - integer

#b - boolean

#u - unsigned integer

#f - float

#C - complex float

#m - timedelta

#M - datetime

#O - object

#S - string

#U - unicode string U

#V - fixed chunk of memory for other type (void)

#checking the datatype of array    (name_of_array.dtype)not make the function

In [ ]:
a = np.array([41, 32, 53, 86, 45, 26, 86, 43, 13, 65, 75])
print(a.dtype)

int64


In [ ]:
a = np.array(["sahil","puja","basanti","varsha"])
print(a.dtype)

<U7


#creating array with define datatype

In [ ]:
a = np.array([41, 32, 53, 86, 45, 26, 86, 43, 13, 65, 75], dtype = "S")
print(a.dtype)
print(a)

|S2
[b'41' b'32' b'53' b'86' b'45' b'26' b'86' b'43' b'13' b'65' b'75']


In [ ]:
#create an array with datatype 4 bytes integer

arr = np.array([1, 2, 3, 4], dtype = 'i4')
print(arr.dtype)
print(arr)

int32
[1 2 3 4]


#numpy array shape

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],[11, 22, 33, 44, 55]])
print(arr.shape)

(2, 5)


In [1]:
import numpy as np
a = np.array([41, 32, 53, 86, 45, 26, 86, 43, 13, 65, 75])
print(a.shape)

(11,)


In [2]:
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr.shape)

(2, 2, 3)


# joining numpy array

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [5]:
#join 2d array

arr1 = np.array([[1, 2, 3],[7, 8, 9]])
arr2 = np.array([[4, 5, 6],[10, 11, 12]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
arr1 = np.array([[1, 2, 3],[7, 8, 9]])
arr2 = np.array([[4, 5, 6],[10, 11, 12]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
print(arr.shape)

[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
(4, 3)


#splitting numpy array

In [8]:
arr =np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
#splitting the array 4 part
arr =np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [16]:
arr2 = np.array([[4, 5, 6],[10, 11, 12]])
arr = np.array_split(arr2, 2)
print(arr)

[array([[4, 5, 6]]), array([[10, 11, 12]])]


#ravel and flatten
convert multidimensional array into 1d array

In [14]:
m = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
print(m)
print("dimension is ",m.ndim)
n = m.ravel()
print(n)
print("new array after applying the ravel and flatten",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
new array after applying the ravel and flatten 1


In [15]:
m = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
print(m)
print("dimension is ",m.ndim)
n = m.flatten()
print(n)
print("new array after applying the ravel and flatten",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
new array after applying the ravel and flatten 1


#unique function

In [17]:
a =np.array([12, 13, 4, 6, 7, 3, 8, 10, 45, 12, 4, 6, 45])
print(a)
x= np.unique(a)
print(x)

[12 13  4  6  7  3  8 10 45 12  4  6 45]
[ 3  4  6  7  8 10 12 13 45]


In [18]:
a =np.array([12, 13, 4, 6, 7, 3, 8, 10, 45, 12, 4, 6, 45])
print(a)
x= np.unique(a, return_index = True)#index no. batayega
print(x)

[12 13  4  6  7  3  8 10 45 12  4  6 45]
(array([ 3,  4,  6,  7,  8, 10, 12, 13, 45]), array([5, 2, 3, 4, 6, 7, 0, 1, 8]))


In [19]:
a =np.array([12, 13, 4, 6, 7, 3, 8, 10, 45, 12, 4, 6, 45])
print(a)
x= np.unique(a, return_index = True, return_counts = True)# index no. aur count kar kae batayega ki kon sa no. kitni baar aa raha
print(x)

[12 13  4  6  7  3  8 10 45 12  4  6 45]
(array([ 3,  4,  6,  7,  8, 10, 12, 13, 45]), array([5, 2, 3, 4, 6, 7, 0, 1, 8]), array([1, 2, 2, 1, 1, 1, 2, 1, 2]))


#delete

In [21]:
a = np.array([12, 34, 65, 30, 56, 56])
d = np.delete(a,[4])#indexing position 4 ko delete kar dega
print(d)

[12 34 65 30 56]


In [24]:
m = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(m)
y= np.delete(m,1, axis = 0)
print()
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]


#Pandas library